$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: my-endpoint
model:
  azureml:whisper-base:latest
code_configuration:
  code: ../onlinescoring/
  scoring_script: score.py
environment: 
  azureml:whisper-base-env:latest
instance_type: Standard_NC6s_v2
instance_count: 1
